CREATE TABLE UserRoles(
    UserId INTEGER NOT NULL REFERENCES Users(Id) ON DELETE CASCADE,
    RoleId INTEGER NOT NULL REFERENCES Roles(Id) ON DELETE CASCADE,
    CreatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (UserId, RoleId)
);

CREATE INDEX IX_UserRoles_UserId ON UserRoles(UserId);
CREATE INDEX IX_UserRoles_RoleId ON UserRoles(RoleId);